name: example
description: >
  The QR.Flutter example app.
version: 2.0.0
homepage: https://github.com/lukef/qr.flutter
publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=3.3.9"

dependencies:
  flutter:
    sdk: flutter
  qr_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
  assets:
    - assets/images/logo_yakka.png
