name: qr_flutter
description: >
  QR.Flutter is a Flutter library for simple and fast QR code rendering via a
  Widget or custom painter.
version: 4.1.0
homepage: https://github.com/theyakka/qr.flutter

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=3.3.9"

dependencies:
  flutter:
    sdk: flutter
  qr: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
